### ISSUE TITLE
在LandscapeRightViewController里添加一个push事件，新vc不会被竖屏

### ISSUE THREAD

**Issue by BoySimonHu** [oymuzi/OMRotate#1]
![image](https://user-images.githubusercontent.com/15783750/57617424-5b211000-75b3-11e9-867c-0780d0e81266.png)

**Comment by oymuzi** [comment]
我刚刚重现了，当push至新页面时，新页面和当前页面的方向不一致时，新页面需要设置页面支持方向，解决方案就是在新页面的viewWillAppear中设置一下页面的方向即可。谢谢你的疑问，将会更新至博客中。
